# Comparação NumPy e Octave
[NumPy for MATLAB users](https://numpy.org/doc/stable/user/numpy-for-matlab-users.html)

In [19]:
import numpy as np
# from scipy import io, integrate, linalg, signal
# from scipy.sparse.linalg import cg, eigs

In [22]:
a = np.array([[1, 2, 3, 7], [4, 5, 6, 8], [7, 8, 9, 9], [10, 11, 12, 10]])
print(a)
print('Último elemento:', a[-1, -1], 'ou', a[-1][-1])
print('Elemento a(3,2):', a[2, 1], 'ou', a[2][1])

[[ 1  2  3  7]
 [ 4  5  6  8]
 [ 7  8  9  9]
 [10 11 12 10]]
Útimo elemento: 10 ou 10
Elemento a(3,2): 8 ou 8


In [21]:
print('Número de dimensões:', a.ndim)
print('Número de elementos:', a.size)
print('Dimensões:', a.shape)

Número de dimensões: 2
Número de elementos: 16
Dimensões: (4, 4)
