# Comparação NumPy e Octave
[NumPy for MATLAB users](https://numpy.org/doc/stable/user/numpy-for-matlab-users.html)

## Equivalência na ÁLgebra Linear

In [147]:
import numpy as np
# from scipy import io, integrate, linalg, signal
# from scipy.sparse.linalg import cg, eigs

In [148]:
a = np.array([[1, 2, 3, 10], [4, 5, 6, 11], [7, 8, 9, 12]])
print(a)

[[ 1  2  3 10]
 [ 4  5  6 11]
 [ 7  8  9 12]]


In [149]:
print('Último elemento:', a[-1, -1], 'ou', a[-1][-1])
print('Elemento a(3,2):', a[2, 1], 'ou', a[2][1])
print('Número de dimensões:', a.ndim)
print('Número de elementos:', a.size)
print('Dimensões:', a.shape)
print('Dimensão 1:', a.shape[0], '| Dimensão 2:', a.shape[1])

Último elemento: 12 ou 12
Elemento a(3,2): 8 ou 8
Número de dimensões: 2
Número de elementos: 12
Dimensões: (3, 4)
Dimensão 1: 3 | Dimensão 2: 4


In [150]:
print('Primeiras duas colunas de a:')
print(a[0:2])
print(a[:2])
print(a[:2, :])

Primeiras duas colunas de a:
[[ 1  2  3 10]
 [ 4  5  6 11]]
[[ 1  2  3 10]
 [ 4  5  6 11]]
[[ 1  2  3 10]
 [ 4  5  6 11]]


In [151]:
print('Últimas duas colunas de a:')
print(a[-2:])

Últimas duas colunas de a:
[[ 4  5  6 11]
 [ 7  8  9 12]]


In [152]:
print('a(2:3,3:4):')
print(a[1:3, 2:4])

a(2:3,3:4):
[[ 6 11]
 [ 9 12]]


In [153]:
print('a(1:2:3):')
print(a[0:3:2])

a(1:2:3):
[[ 1  2  3 10]
 [ 7  8  9 12]]


In [154]:
print("Transpostas de a:")
print(a.transpose())
print(a.T)

Transpostas de a:
[[ 1  4  7]
 [ 2  5  8]
 [ 3  6  9]
 [10 11 12]]
[[ 1  4  7]
 [ 2  5  8]
 [ 3  6  9]
 [10 11 12]]


In [155]:
print('Transposta conjugada de a:')
print(a.conj().transpose())
print(a.conj().T)

Transposta conjugada de a:
[[ 1  4  7]
 [ 2  5  8]
 [ 3  6  9]
 [10 11 12]]
[[ 1  4  7]
 [ 2  5  8]
 [ 3  6  9]
 [10 11 12]]


In [156]:
b = np.array([[9, 5, 1], [6, 2, 7], [3, 8, 4], [7, 5, 3]])
print(b)

[[9 5 1]
 [6 2 7]
 [3 8 4]
 [7 5 3]]


In [157]:
print('Multiplicação matricial (a*b):')
print(a @ b)

Multiplicação matricial (a*b):
[[100  83  57]
 [161 133  96]
 [222 183 135]]


In [158]:
print("Multiplicação elemento a elemento (a'.*b):")
print(a.T * b)

Multiplicação elemento a elemento (a'.*b):
[[ 9 20  7]
 [12 10 56]
 [ 9 48 36]
 [70 55 36]]


In [159]:
print("Divisão elemento a elemento (a'./b):")
print(a.T / b)

Divisão elemento a elemento (a'./b):
[[0.11111111 0.8        7.        ]
 [0.33333333 2.5        1.14285714]
 [1.         0.75       2.25      ]
 [1.42857143 2.2        4.        ]]


In [160]:
print('Exponencação elemento a elemento (a^3):')
print(a**3)

Exponencação elemento a elemento (a^3):
[[   1    8   27 1000]
 [  64  125  216 1331]
 [ 343  512  729 1728]]


In [161]:
print('Comparação entre valores (a>5):')
print(a > 5)

Comparação entre valores (a>5):
[[False False False  True]
 [False False  True  True]
 [ True  True  True  True]]


In [162]:
c = a.copy()
print(c)

[[ 1  2  3 10]
 [ 4  5  6 11]
 [ 7  8  9 12]]


In [163]:
print('Range de 1 a 10:')
print(np.array(range(1, 11)))
print(np.arange(1, 11))
print(np.r_[1:11])

Range de 1 a 10:
[ 1  2  3  4  5  6  7  8  9 10]
[ 1  2  3  4  5  6  7  8  9 10]
[ 1  2  3  4  5  6  7  8  9 10]


In [164]:
print('Range de 0 a 9:')
print(np.array(range(10)))
print(np.arange(10))
print(np.r_[:10])

Range de 0 a 9:
[0 1 2 3 4 5 6 7 8 9]
[0 1 2 3 4 5 6 7 8 9]
[0 1 2 3 4 5 6 7 8 9]


In [165]:
print("Vetor coluna de 0 a 9 ([0:9]'):")
print(np.arange(10)[:, np.newaxis])

Vetor coluna de 0 a 9 ([0:9]'):
[[0]
 [1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]
 [9]]


In [166]:
print('Matriz 3 x 4 de zeros:')
print(np.zeros((3, 4)))

Matriz 3 x 4 de zeros:
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [167]:
print('Matriz 3 x 4 de uns:')
print(np.ones((3, 4)))

Matriz 3 x 4 de uns:
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [168]:
print('Matriz identidade 4 x 4:')
print(np.eye(4))

Matriz identidade 4 x 4:
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [169]:
print('Vetor diagonal de a:')
print(np.diag(a))

Vetor diagonal de a:
[1 5 9]


In [170]:
print('Intervalo de 0 a 100 dividino em 5 elementos:')
print(np.linspace(0, 100, 5))

Intervalo de 0 a 100 dividino em 5 elementos:
[  0.  25.  50.  75. 100.]
