# Comparação NumPy e Octave
[NumPy for MATLAB users](https://numpy.org/doc/stable/user/numpy-for-matlab-users.html)

## Equivalência na Álgebra Linear

In [498]:
import numpy as np
from scipy import io, integrate, linalg, signal
from scipy.sparse.linalg import cg, eigs

In [499]:
print('Matriz a:')
a = np.array([[1, 2, 3, 10], [4, 5, 6, 11], [7, 8, 9, 12]])
print(a)

Matriz a:
[[ 1  2  3 10]
 [ 4  5  6 11]
 [ 7  8  9 12]]


In [500]:
print('Último elemento:', a[-1, -1], 'ou', a[-1][-1])
print('Elemento a(3,2):', a[2, 1], 'ou', a[2][1])
print('Número de dimensões:', a.ndim)
print('Número de elementos:', a.size)
print('Dimensões:', a.shape)
print('Dimensão 1:', a.shape[0], '| Dimensão 2:', a.shape[1])

Último elemento: 12 ou 12
Elemento a(3,2): 8 ou 8
Número de dimensões: 2
Número de elementos: 12
Dimensões: (3, 4)
Dimensão 1: 3 | Dimensão 2: 4


In [501]:
print('Primeiras duas colunas de a:')
print(a[0:2])
print(a[:2])
print(a[:2, :])

Primeiras duas colunas de a:
[[ 1  2  3 10]
 [ 4  5  6 11]]
[[ 1  2  3 10]
 [ 4  5  6 11]]
[[ 1  2  3 10]
 [ 4  5  6 11]]


In [502]:
print('Últimas duas colunas de a:')
print(a[-2:])

Últimas duas colunas de a:
[[ 4  5  6 11]
 [ 7  8  9 12]]


In [503]:
print('a(2:3,3:4):')
print(a[1:3, 2:4])

a(2:3,3:4):
[[ 6 11]
 [ 9 12]]


In [504]:
print('a(1:2:3):')
print(a[0:3:2])

a(1:2:3):
[[ 1  2  3 10]
 [ 7  8  9 12]]


In [505]:
print("Transpostas de a:")
print(a.transpose())
print(a.T)

Transpostas de a:
[[ 1  4  7]
 [ 2  5  8]
 [ 3  6  9]
 [10 11 12]]
[[ 1  4  7]
 [ 2  5  8]
 [ 3  6  9]
 [10 11 12]]


In [506]:
print('Transposta conjugada de a:')
print(a.conj().transpose())
print(a.conj().T)

Transposta conjugada de a:
[[ 1  4  7]
 [ 2  5  8]
 [ 3  6  9]
 [10 11 12]]
[[ 1  4  7]
 [ 2  5  8]
 [ 3  6  9]
 [10 11 12]]


In [507]:
print('Matriz b:')
b = np.array([[9, 5, 1], [6, 2, 7], [3, 8, 4], [7, 5, 3]])
print(b)

Matriz b:
[[9 5 1]
 [6 2 7]
 [3 8 4]
 [7 5 3]]


In [508]:
print('Multiplicação matricial (a*b):')
print(a @ b)

Multiplicação matricial (a*b):
[[100  83  57]
 [161 133  96]
 [222 183 135]]


In [509]:
print("Multiplicação elemento a elemento (a'.*b):")
print(a.T * b)

Multiplicação elemento a elemento (a'.*b):
[[ 9 20  7]
 [12 10 56]
 [ 9 48 36]
 [70 55 36]]


In [510]:
print("Divisão elemento a elemento (a'./b):")
print(a.T / b)

Divisão elemento a elemento (a'./b):
[[0.11111111 0.8        7.        ]
 [0.33333333 2.5        1.14285714]
 [1.         0.75       2.25      ]
 [1.42857143 2.2        4.        ]]


In [511]:
print('Exponencação elemento a elemento (a^3):')
print(a**3)

Exponencação elemento a elemento (a^3):
[[   1    8   27 1000]
 [  64  125  216 1331]
 [ 343  512  729 1728]]


In [512]:
print('Comparação entre valores (a>5):')
print(a > 5)

Comparação entre valores (a>5):
[[False False False  True]
 [False False  True  True]
 [ True  True  True  True]]


In [513]:
print('Matriz c:')
c = a.copy()
print(c)

Matriz c:
[[ 1  2  3 10]
 [ 4  5  6 11]
 [ 7  8  9 12]]


In [514]:
print('Range de 1 a 10:')
print(np.array(range(1, 11)))
print(np.arange(1, 11))
print(np.r_[1:11])

Range de 1 a 10:
[ 1  2  3  4  5  6  7  8  9 10]
[ 1  2  3  4  5  6  7  8  9 10]
[ 1  2  3  4  5  6  7  8  9 10]


In [515]:
print('Range de 0 a 9:')
print(np.array(range(10)))
print(np.arange(10))
print(np.r_[:10])

Range de 0 a 9:
[0 1 2 3 4 5 6 7 8 9]
[0 1 2 3 4 5 6 7 8 9]
[0 1 2 3 4 5 6 7 8 9]


In [516]:
print("Vetor coluna de 0 a 9 ([0:9]'):")
print(np.arange(10)[:, np.newaxis])

Vetor coluna de 0 a 9 ([0:9]'):
[[0]
 [1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]
 [9]]


In [517]:
print('Matriz 3 x 4 de zeros:')
print(np.zeros((3, 4)))

Matriz 3 x 4 de zeros:
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [518]:
print('Matriz 3 x 4 de uns:')
print(np.ones((3, 4)))

Matriz 3 x 4 de uns:
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [519]:
print('Matriz identidade 4 x 4:')
print(np.eye(4))

Matriz identidade 4 x 4:
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [520]:
print('Vetor diagonal de a:')
print(np.diag(a))

Vetor diagonal de a:
[1 5 9]


In [521]:
print('Intervalo de 0 a 100 dividino em 5 elementos:')
print(np.linspace(0, 100, 5))

Intervalo de 0 a 100 dividino em 5 elementos:
[  0.  25.  50.  75. 100.]


In [522]:
print('Matriz 4 x 5 de elementos iguais a 3:')
print(np.tile(3, (4, 5)))

Matriz 4 x 5 de elementos iguais a 3:
[[3 3 3 3 3]
 [3 3 3 3 3]
 [3 3 3 3 3]
 [3 3 3 3 3]]


In [523]:
print('Matriz d:')
d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(d)

Matriz d:
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [524]:
print('Matriz e:')
e = np.array([[11, 12, 13], [14, 15, 16], [17, 18, 19]])
print(e)

Matriz e:
[[11 12 13]
 [14 15 16]
 [17 18 19]]


In [525]:
print('Concatenar colunas [d e]:')
print(np.concatenate((d, e), 1))
print(np.hstack((d, e)))
print(np.c_[d, e])

Concatenar colunas [d e]:
[[ 1  2  3 11 12 13]
 [ 4  5  6 14 15 16]
 [ 7  8  9 17 18 19]]
[[ 1  2  3 11 12 13]
 [ 4  5  6 14 15 16]
 [ 7  8  9 17 18 19]]
[[ 1  2  3 11 12 13]
 [ 4  5  6 14 15 16]
 [ 7  8  9 17 18 19]]


In [526]:
print('Concatenar linhas [d; e]:')
print(np.concatenate((d, e)))
print(np.vstack((d, e)))
print(np.r_[d, e])

Concatenar linhas [d; e]:
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [11 12 13]
 [14 15 16]
 [17 18 19]]
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [11 12 13]
 [14 15 16]
 [17 18 19]]
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [11 12 13]
 [14 15 16]
 [17 18 19]]


In [527]:
print('Máximo elemento de a:', a.max())
print('Máximo elemento de cada coluna de a:', a.max(0))
print('Máximo elemento de cada linha de a:', a.max(1))

Máximo elemento de a: 12
Máximo elemento de cada coluna de a: [ 7  8  9 12]
Máximo elemento de cada linha de a: [10 11 12]


In [528]:
print('Matriz A:')
A = np.array([[2, 1, -1], [1, 3, 2], [3, -2, 1]])
print(A)

Matriz A:
[[ 2  1 -1]
 [ 1  3  2]
 [ 3 -2  1]]


In [529]:
print('Vetor B:')
B = np.array([3, 4, -5]) #[:, np.newaxis]
print(B)

Vetor B:
[ 3  4 -5]


In [530]:
print('Iversa de A:')
print(linalg.inv(A))

Iversa de A:
[[ 0.23333333  0.03333333  0.16666667]
 [ 0.16666667  0.16666667 -0.16666667]
 [-0.36666667  0.23333333  0.16666667]]


In [531]:
print('Resultado de A x = B (x = A\B):')
# B pode ser um vetor coluna ou linha. A resposta será dada na respectiva forma.
x = linalg.solve(A, B)
print(x)

Resultado de A x = B (x = A\B):
[ 0.  2. -1.]


In [532]:
# print(Se A não for uma matriz quadrada, a solução de A x = B pode ser dada por:)
# x = linalf.lstsq(A, B)
# print(x)

In [533]:
print('Vetor com os valores únicos de A:')
print(np.unique(A))

Vetor com os valores únicos de A:
[-2 -1  1  2  3]
